name = "homebrew-store-repo"
compatibility_date = "2026-03-18"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"
minify = true

[placement]
mode = "smart"

[site]
bucket = "./assets"

[vars]
BASELINK = "store-cdn.repressoh.it"
