name = "homebrew-store-repo"
compatibility_date = "2024-04-06"
node_compat = true
main = "src/index.ts"
minify = true

[placement]
mode = "smart"

[site]
bucket = "./assets"

[vars]
BASELINK = "store-cdn.repressoh.it"